### ISSUE TITLE
html/en/website at the wrong position

### ISSUE THREAD

**Issue by haraldschilly** [sagemath/documentation#1]
I don't know where that page is usually located, but right now it's at the wrong position. At least, it shouldn't show up in the overall index.

**Comment by SilentFlame** [comment]
@haraldschilly I would like too fix this thing. can you please tell me what exactly I have to do?

**Comment by haraldschilly** [comment]
@VinaySingh035 well, figuring out what to do is the complex part. looking at this again, I think nothing needs to be done at all. it's this page here http://doc.sagemath.org/html/en/ and the links do work.
