### ISSUE TITLE
Broken buttons

### ISSUE THREAD

**Issue by theo-armour** [sagemath/documentation#12]
Go to http://doc.sagemath.org/ > 'A Tour of Sage' > http://doc.sagemath.org/html/en/a_tour_of_sage/index.html

Click 'Activate; button at top right

'Run' buttons appear under all the examples.

Click any of the run buttons

Text on all the run buttons changes to 'Disconnected from Server / Attempting to reconnect'

And then nothing happens...

**Comment by haraldschilly** [comment]
Hi, I'm seeing this for the first time, must be new.

**Comment by haraldschilly** [comment]
reported it here: https://groups.google.com/d/topic/sage-devel/lP4qrWZBDsI/discussion

**Comment by haraldschilly** [comment]
There is now a patch, part of this repo here, disabling this entirely. Someone should fix this in SageMath properly, though!!!
