### ISSUE TITLE
Documentation needs updating for Sage 9.2

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/documentation#23]

**Comment by haraldschilly** [comment]
ok, I've triggered a new build and well, there must be a missing file or dangling symlink. error is:

> The symbolic link `/pdf/en/reference/_static` targets a file which does not exist within your site's repository.

I guess something changed here from 9.1 to 9.2

**Comment by haraldschilly** [comment]
fixed via 35a60f7c1823547aa2312c045690d85c58eb9920
