### ISSUE TITLE
Page does not exist: http://www.friedspace.com/QS/

### ISSUE THREAD

**Issue by rickhg12hs** [sagemath/documentation#25]
Stale link?

https://github.com/sagemath/documentation/blob/445b7aef505eabde274d2489c4d3beeea7c5f314/html/en/reference/spkg/flintqs.html#L63

It's not clear to me how we should report such things.  I see the link to the Trac site but I don't know how to report there ... or even if it's possible.  Perhaps some instructions in the `README.md` would be helpful.

**Comment by haraldschilly** [comment]
This project here is just the facilitator to transform the sage source code to the pages you see online. Hence, this must be reported at sage's bugtracker: https://trac.sagemath.org

**Comment by rickhg12hs** [comment]
Done!

https://trac.sagemath.org/ticket/31733#ticket
