### ISSUE TITLE
Mangled main PDF reference index

### ISSUE THREAD

**Issue by paulmasson** [sagemath/documentation#8]
The document at http://doc.sagemath.org/pdf/en/reference/ is missing text compared to the HTML version and has a few badly formatted links at the end. Even stranger, the main "Sage" link in the upper left corner points to a project file of some sort that does not exist.

Since I'm not sure how this file is generated, I don't know how to fix this or I would.

**Comment by haraldschilly** [comment]
Hmm, I think I saw that once. My understanding is, that the whole reference is too large to be processed by sphinx. Therefore it is split into subchapters. Parts of that page are probably [this index file](https://github.com/sagemath/sage/blob/master/src/doc/en/reference/index.rst).

But I don't know where the remainder comes. Maybe it has something to do with conf.py and conf_sub.py in that [very same directory](https://github.com/sagemath/sage/tree/master/src/doc/en/reference) ?

**Comment by haraldschilly** [comment]
Hi, I'm going through the documentation issues. This one is entirely an upstream issue. I have no idea if there is a trac ticket for this. Looks like it's just a matter of fixing some index file for sphinx to get this right ...
