### ISSUE TITLE
Links in indices missing path component to notebook pages

### ISSUE THREAD

**Issue by paulmasson** [sagemath/documentation#9]
In the folder `html/en/reference`, several genindex-*.html files (notably genindex-N.html) have bad links to documentation for the legacy notebook. The links all start with `sagenb/` when they should start with `notebook/sagenb/`. The indices in `html/en/reference/notebook` are fine, since those links start with the correct `sagenb/`.

This presumably happens because the notebook files are not part of the main repository and need to be included manually when generating documentation pages. It's a minor issue but it does produce errors in the indexing, so as long as the legacy notebook is part of the documentation please be aware of this.

**Comment by theo-armour** [comment]
Maybe this is connected:

http://www.sagemath.org/ > help menu > Tutorial

Takes you to:

http://doc.sagemath.org/html/en/tutorial/

Click 'installation'

On this line, click the link at the end

If you do not have Sage installed on a computer and just want to try some commands, use online at http://www.sagenb.org.

Receive this message:

The www.sagenb.org page isn’t working

www.sagenb.org redirected you too many times.

**Comment by haraldschilly** [comment]
sagenb.org no longer exists. All mentions of sagenb.org should change to the sage cell (not sure about sagemathcloud, but it's also an option to run sage online), and that should be reported at https://trac.sagemath.org/ to fix the documentation.

Did you check if there is a ticket on trac to fix the documentation about sagenb.org?

**Comment by theo-armour** [comment]
@haraldschilly 

> Did you check if there is a ticket on trac to fix the documentation about sagenb.org?

I am not a SageMath developer or user, just an occasional visitor informing you of something I observed. I will let others take care of any follow-up.

**Comment by paulmasson** [comment]
https://trac.sagemath.org/ticket/22436

**Comment by haraldschilly** [comment]
the mentioned upstream ticket is closed, hence closing this one. if something similar pops up (related to the actual content!), please report it at trac
